name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: true
      - name: Run tests
        run: uv run pytest tests/ --cov=src/examui --cov-report=term-missing | tee pytest-coverage.txt
      - name: Format coverage report
        if: always()
        id: coverage
        uses: MishaKav/pytest-coverage-comment@v1
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          default-branch: master
          hide-comment: true
      - name: Write job summary
        if: always()
        run: echo '${{ steps.coverage.outputs.coverageHtml }}' >> "$GITHUB_STEP_SUMMARY"
